name: stop_watch_timer
description: This is Stop Watch Timer for flutter plugin. It easily create application of stop watch for sports if use this plugin.
version: 0.6.0+1
repository: https://github.com/hukusuke1007/stop_watch_timer
homepage: https://github.com/hukusuke1007/stop_watch_timer

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: 1.10.0+2
